name: Build Docker Images

on:
  workflow_dispatch:
  #schedule:
    #- cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - images/**

jobs:
  push:
    name: "Build pterodactyl:${{ matrix.images }} Image"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        images:
          - steam
          - steam-installer
    steps:
      - uses: actions/checkout@v5.0.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./images/${{ matrix.images }}
          file: ./images/${{ matrix.images }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/leliel91/${{ matrix.images }}:latest

  cleanup:
    name: Purge old GHCR images
    needs: push
    runs-on: ubuntu-latest
    strategy:
      matrix:
        images:
          - steam
          - steam-installer
    steps:
      - name: Cleanup untagged GHCR images
        uses: actions/delete-package-versions@v5
        with:
          delete-only-untagged-versions: 'true'
          min-versions-to-keep: 10
          package-name: '${{ matrix.images }}'
          package-type: 'container'