name: build os
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - os/**
jobs:
  push:
    name: "pterodactyl:${{ matrix.os }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - alpine
          - debian
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: ./os/${{ matrix.os }}
          file: ./os/${{ matrix.os }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/leliel91/pterodactyl:${{ matrix.os }}
